### PR TITLE
Added dark icons and background; Updated some build settings for Mojave

### PR DESCRIPTION
**Pull request by skytect**
I haven't updated it to Swift 4.2 because I haven't figured out how to fix this error in ClipperViewController.swift

error

### CODE REVIEW

**Comment by Savjee** [comment]
Thanks for the PR! I will test it out once I have Mojave running.

Quick question beforehand: I did include a dark icon with the app. Didn't that work out of the box on Mojave? Has something changed there?

**Comment by skytect** [comment]
The menu bar icon worked out of the box. However, the settings and screenshot buttons remained black. The background for the text view also didn't change. So, I inverted the colors for the button icons when set to dark mode in assets. I also changed the text view's background color to "Window Background Color" in main.storyboard.

**Comment by Savjee** [comment]
Sorry for the late reply! Only got around to this now.

Can you check out v1.1.0-beta1 and test if it works correctly on Mojave?
https://github.com/Savjee/bearclaw/releases/download/v1.1.0-beta1/bearclaw-v1.1.0-beta1.zip

Thanks!

**Comment by Savjee** [comment]
Update: tested the new version on Mojave and dark mode now works.
Thanks for you code!

**Pull request closed without merging**
